### PR TITLE
Update PHP_ICO to PHP5, as close to PSR-2 as possible.

### PR DESCRIPTION
**Pull request by ossobuffo**
Since PHP4 is no longer in active service, and since [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) is the prevailing standard, I thought it was time that PHP_ICO got the update it has long deserved. Indeed, many aspects of PHP4-style class structure will not work in PHP7, so doing this is future-proofing the class.

This update is not 100% PSR-2 compliant, for backwards compatibility reasons. Users should be able to upgrade to this version without experiencing breakage.
1. The class is not namespaced.
2. The class name itself is not PSR-2 compliant, because it is not camelCase.
3. Public methods are still in snake_case. Private methods and all internal variables were converted to camelCase.

Since things like namespaces, anonymous functions and short array syntax were not used, this should still work for PHP versions as ancient as 5.0.

### CODE REVIEW

**Comment by IceReaper** [comment]
Maybe a good point to start refactoring the class fully PSR-2 compliant, and make the original file / class a wrapper class?

**Comment by ossobuffo** [comment]
The PhpIco class is now fully PSR-2 compliant, and can be autoloaded via composer. the PHP_ICO class is a non-PSR-2 compliant wrapper class.

**Comment by IceReaper** [comment]
Any chance on getting this up on packagist soon?

**Comment by ossobuffo** [comment]
I may publish my fork to packagist in a couple weeks. I don't think @chrisbliss18 monitors this repository much.

**Comment by ossobuffo** [comment]
After some research, I'm recommending that users use https://packagist.org/packages/signpostmarv/php-ico instead of my branch, since it has support for not only gd but also imagemagick (via the intervention/image dependency). It will require a bit of adaptation of existing code, but it appears to be more robust than my version.

Note that that implementation does not have a save_ico() method. You'll have to call getIcoData() and write the resulting string to a file.

**Comment by SignpostMarv** [comment]
@ossobuffo I've put the original code onto the old-master branch.

**Pull request closed without merging**
